config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    # resources :users
    resources :locations
    resources :pets
    resources :pet_categories
    # resources :user_details

    root to: "pets#index"
  end

  devise_for :users
  resources :pets, except: :destroy
  resources :locations, except: :destroy
  resources :pet_categories, except: :destroy
  resources :landing_page, only: :show
  root 'pets#index'
end

app/models/pet.rb
class Pet < ApplicationRecord
  # Alternatively could do mod 1000, 100, 10, 1 for visibility ... 
  # ... anything ending in 0 is invisible, 1 is visible on index to every, ...
  # ... 2 owner, 3 mod, 4 admin.   Then the range actual value is progression ...
  # ... thru the life cycle
  #
  # - Current status
  # first 10,000 are user status, 20k's are business status, 30k's are anti-troll
  # posts after 5000 don't have to show up in the general display queries 
  enum pet_status: {
    draft: 5000, published: 200, sold: 4000, cancelled: 5200,
    billing: 20000, ready_for_fulfillment: 20200, fulfilling_processing: 20400,
    removed: 30000, suspended: 30200, banned: 30400 }

  belongs_to :pet_category
  belongs_to :location
  belongs_to :user_detail, inverse_of: :pets
  
  validates_presence_of :name
  validates_presence_of :pet_category_id
  validates_presence_of :location_id
  validates_presence_of :user_detail_id
  validates_presence_of :pet_status
  # validates_inclusion_of :pet_status, :in => 0..35000, :allow_nil => true, :message => 'must be between 3 and 8 feet'


  scope :transactions,  -> { where('pet_status = ?', 4000) }
  scope :drafts,        -> { where('pet_status = ?', 4000) }
  scope :test_scope,    -> { where('pet_status > ?', 1)    }
  scope :test_scope2,   -> { where('pet_status < ?', 5500) }
end

app/controllers/admin/pets_controller.rb
module Admin
  class PetsController < Admin::ApplicationController
    before_action :authenticate_admin
### TODO remove if not needed - start!
    include Administrate::Punditize
    

    def authenticate_admin
      # TODO Add authentication logic here.
      authenticate_user!
    end

    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    def index
      # byebug
      @user_resources = current_user.user_detail.pets
      @resources = @user_resources.page(params[:page]).per(10)
      super
    end

    def create
      @current_owner = current_user.user_detail # required for assoc relationship
      params['pet']['user_detail_id'] = @current_owner.id
      super 
    end
    
    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Pet.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions

  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
  # @pets = Pet.all
  # byebug
    @pets = policy_scope(Pet)
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
    authorize @pet
    
  end

  # GET /pets/1/edit
  def edit
    authorize @pet
  end

  # POST /pets
  # POST /pets.json
  def create
    @user = current_user.user_detail # required for assoc relationship
    @pet = @user.pets.build(pet_params)
    authorize @pet
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    authorize @pet
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  # def destroy
  #   @pet.destroy
  #   respond_to do |format|
  #     format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    def set_pet
      @pet = Pet.find(params[:id])
    end

    def pet_params
      params.require(:pet).permit(:name, :pet_status, :description, :pet_category_id, :location_id, :published, :visible, :available, :user_detail_id)
    end
    
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.haml
- if @pet.errors.any?
  Please review the following messages ...
  - @pet.errors.full_messages.each do |msg|
    %li= msg
= simple_form_for(@pet) do |f|
  // = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.association :pet_category
    = f.association :location
    = f.label "Pet Status"
    = f.select :pet_status, Pet.pet_statuses.keys.map { |w| [w.humanize, w] }
    = f.input :published
    = f.input :available, inline_label: 'Available' 
    = f.input :visible, inline_label: 'Visible'

  .form-actions
    = f.button :submit

app/views/pets/edit.html.haml
.header
  %h1 Editing pet

.content
  = render 'form'
  
  = link_to 'Show', @pet
  \|
  = link_to 'Back', pets_path

app/views/pets/index.html.haml
.header
  %h1 Listing pets 

.content
  %table{class: 'pure-table'}
    %thead
      %tr
        %th Name
        %th Description
        %th Pet categories
        %th Location
        %th Status
        %th Published
        %th Available
        %th Owner
        // %th
        // %th
  
    %tbody
      // = @pets.count
      // = debug(@pets.first)
      // - @pets.each do |pet|
      - if @pets.count > 0
        - @pets.each do |pet|
          %tr
            %td= pet.name
            %td= pet.description
            %td= pet.pet_category.name
            %td= pet.location.name
            %td= pet.pet_status.titleize 
            %td= pet.published
            %td= pet.available
            - if pet.user_detail 
              %td= pet.user_detail.name
            - else 
              %td= "Crap"
            // %td= pet.user_detail.name
            // %td= pet.user_detail.first.name
            %td= link_to 'Show', pet
            - if policy(pet).edit?
              %td= link_to 'Edit', edit_pet_path(pet)


  %br
  
  // = link_to 'New Pet', new_pet_path

app/views/pets/new.html.haml
.header
  %h1 New pet

.content
  = render 'form'
  
  = link_to 'Back', pets_path

app/views/pets/show.html.haml
.content
  %p#notice= notice
  
  %p
    %b Name:
    = @pet.name
  %p
    %b Description:
    = @pet.description
  %p
    %b Pet categories:
    = @pet.pet_category.name
  %p
    %b Pet Status:
    = @pet.pet_status.titleize 
  %p
    %b Pet Available:
    = @pet.available
  %p
    %b Location:
    = @pet.location.name
  
  - if policy(@pet).update?
    = link_to 'Edit', edit_pet_path(@pet)
    \|
  = link_to 'Back', pets_path