config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    # resources :users
    resources :locations
    resources :pets
    resources :pet_categories
    # resources :user_details

    root to: "pets#index"
  end

  devise_for :users
  resources :pets, except: :destroy
  resources :locations, except: :destroy
  resources :pet_categories, except: :destroy
  resources :landing_page, only: :show
  root 'pets#index'
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    # include Pundit
    include Administrate::Punditize
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
      authenticate_user!
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
    
      
  rescue_from Pundit::NotAuthorizedError, with: :admin_user_not_authorized
 
  private
 
    def admin_user_not_authorized
      flash[:warning] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
      # redirect_to(root_path)
      # raise
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # important to note - this means either no user provided in addition to bad creditionals or permissions
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # rescue_from NoUserProvidedError, with: :no_user_provided
  
  # class NoUserProvidedError < Pundit::NotAuthorizedError 
  #   super
  # end
 
  private
 
    def user_not_authorized(exception)
      # TODO segment out the non not-authorized errors
      flash[:warning] = "Not authorized ... #{exception}."
      # redirect_to(request.referrer || root_path)
      # redirect_to(root_path)
      redirect_to '/landing_page/show'
      # render 'layouts/login' #  TODO set this to render login when failure
      # raise
    end
    
    def no_user_provided
      flash[:warning] = "No user provided to Pundit Gem to authorize against."
      redirect_to '/landing_page/show'
    end
  

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return this to use in /app/views/layouts/_login.html.haml
  def get_user_name
    current_user ? current_user&.user_detail&.name : ""
  end
end

app/views/admin/application/_flashes.html.erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>"><%= value.html_safe %></div>
    <% end -%>
  </div>
<% end %>

app/views/admin/application/_javascript.html.erb
<%#
# Javascript Partial

This partial imports the necessary javascript on each page.
By default, it includes the application JS,
but each page can define additional JS sources
by providing a `content_for(:javascript)` block.
%>

<% Administrate::Engine.javascripts.each do |js_path| %>
  <%= javascript_include_tag js_path %>
<% end %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/admin/application/_login.html.haml
- if user_signed_in?
  %li{:class => 'navigation__link'}
    = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'pure-menu-link'
  %li{:class => 'navigation__link'}
    = link_to "User: #{current_user ? current_user.user_detail.name : ''}", admin_root_url, class: 'pure-menu-link'

- else
  = link_to 'Log In', new_user_session_path, class: 'pure-menu-link'
  = link_to 'Sign up', new_user_registration_path, class: 'pure-menu-link'

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation" role="navigation">
  <% Administrate::Namespace.new(namespace).resources.each do |resource| %>
    <%= link_to(
      display_resource_name(resource),
      [namespace, resource_index_route_key(resource)],
      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
    ) %>
  <% end %>
  <div class = "navigation__link">
    <%= link_to "Back to Shopping", '/' %>
  </div>
  <%= render 'login'  %>
</nav>

app/views/admin/application/_stylesheet.html.erb
<%#
# Stylesheet Partial

This partial imports the necessary stylesheets on each page.
By default, it includes the application CSS,
but each page can define additional CSS sources
by providing a `content_for(:stylesheet)` block.
%>

<% Administrate::Engine.stylesheets.each do |css_path| %>
  <%= stylesheet_link_tag css_path %>
<% end %>

<%= yield :stylesheet %>

app/views/admin/application/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <%= link_to(
      t(
        "administrate.actions.new_resource",
        name: page.resource_name.titleize.downcase
      ),
      [:new, namespace, page.resource_path],
      class: "button",
    ) if valid_action?(:new) && show_action?(:new, new_resource) %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>

<%= render 'flashes' %>