config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    # resources :users
    resources :locations
    resources :pets
    resources :pet_categories
    # resources :user_details

    root to: "pets#index"
  end

  devise_for :users
  resources :pets, except: :destroy
  resources :locations, except: :destroy
  resources :pet_categories, except: :destroy
  resources :landing_page, only: :show
  root 'pets#index'
end

app/models/pet_category.rb
class PetCategory < ApplicationRecord
    has_many :pets
    validates_presence_of :name
end

app/controllers/admin/pet_categories_controller.rb
module Admin
  class PetCategoriesController < Admin::ApplicationController

    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    def index
      super
      @resources = PetCategory.
        page(params[:page]).
        per(10)
        @user = current_user
    end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   PetCategory.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/pet_categories_controller.rb
class PetCategoriesController < ApplicationController
  before_action :set_pet_category, only: [:show, :edit, :update, :destroy]

  # GET /pet_categories
  # GET /pet_categories.json
  def index
    @pet_categories = PetCategory.all
  end

  # GET /pet_categories/1
  # GET /pet_categories/1.json
  def show
  end

  # GET /pet_categories/new
  def new
    @pet_category = PetCategory.new
  end

  # GET /pet_categories/1/edit
  def edit
  end

  # POST /pet_categories
  # POST /pet_categories.json
  def create
    @pet_category = PetCategory.new(pet_category_params)

    respond_to do |format|
      if @pet_category.save
        format.html { redirect_to @pet_category, notice: 'Pet category was successfully created.' }
        format.json { render :show, status: :created, location: @pet_category }
      else
        format.html { render :new }
        format.json { render json: @pet_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_categories/1
  # PATCH/PUT /pet_categories/1.json
  def update
    respond_to do |format|
      if @pet_category.update(pet_category_params)
        format.html { redirect_to @pet_category, notice: 'Pet category was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet_category }
      else
        format.html { render :edit }
        format.json { render json: @pet_category.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_category
      @pet_category = PetCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_category_params
      params.require(:pet_category).permit(:name, :description)
    end
end

app/helpers/pet_categories_helper.rb
module PetCategoriesHelper
end

app/views/pet_categories/_form.html.haml
= simple_form_for(@pet_category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/pet_categories/edit.html.haml
.header
  %h1 Editing pet_category
.content
  = render 'form'
  
  = link_to 'Show', @pet_category
  \|
  = link_to 'Back', pet_categories_path

app/views/pet_categories/index.html.haml
.header
  %h1 Listing Pet Categories

.content
  %table{class: 'pure-table'}
    %thead
      %tr
        %th Name
        %th Description
        %th
        %th

    %tbody
      - @pet_categories.each do |pet_category|
        %tr
          %td= pet_category.name
          %td= pet_category.description
          %td= link_to 'Show', pet_category
          %td= link_to 'Edit', edit_pet_category_path(pet_category)
  %br
  
  = link_to 'New Pet category', new_pet_category_path

app/views/pet_categories/new.html.haml
.content
  %h1 New Pet Category
  
  = render 'form'
  
  = link_to 'Back', pet_categories_path

app/views/pet_categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @pet_category.name
%p
  %b Description:
  = @pet_category.description

= link_to 'Edit', edit_pet_category_path(@pet_category)
\|
= link_to 'Back', pet_categories_path